#!/usr/bin/env bash

dir='/usr/share/X11/xkb/symbols'
thisDir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
symbols="$thisDir/teck_se"
symbolsToReplace="$dir/au"
symbolsToReplaceCopy="$thisDir/au-backup"
symbolsToPatch1="$dir/inet"

comment=''

case "$1" in
  install )
    comment='//'
    echo 'Installing…'
    ;;
  uninstall )
    echo 'Uninstalling…'
    ;;
  * )
    echo "Usage: $0 (install|uninstall)"
    echo ''
    echo 'You probably need to run this with sudo.'
    echo ''
    echo "$0 install"
    echo ''
    echo '  Replaces'
    echo "  $symbolsToReplace"
    echo '  with a symlink to'
    echo "  $symbols"
    echo ''
    echo '  Comments out lines defining F13–F20 in'
    echo "  $symbolsToPatch1"
    echo ''
    echo "$0 uninstall"
    echo ''
    echo '  Replaces'
    echo "  $symbolsToReplace"
    echo '  with a copy of'
    echo "  $symbolsToReplaceCopy"
    echo '  which comes from'
    echo '  https://cgit.freedesktop.org/xkeyboard-config/tree/symbols/au?id=8791fd60ca031441fbe5b137d8587e0285490fb1'
    echo ''
    echo '  Uncomments lines defining F13–F20 in'
    echo "  $symbolsToPatch1"
    echo ''
    echo 'It is safe to run install or uninstall several times in a row.'
    exit 1
    ;;
esac

echoRun() {
  cmd="$*"
  echo "$cmd"
  $cmd
}

toggleComment() {
  regex="$1"
  file="$2"
  echoRun sed -E -i \
    's#^(//)?(.+'"$regex"')#'"$comment"'\2#' \
    "$file"
}

if test -z "$comment"; then
  echoRun cp --remove-destination "$symbolsToReplaceCopy" "$symbolsToReplace"
else
  echoRun ln -s -f "$symbols" "$symbolsToReplace"
fi

toggleComment 'FK(1[3-9]|20)' "$symbolsToPatch1"

echo 'Done.'
